[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_grid = "A85D8jc1K2ksr2kRip2XVYrdi25qddR3MMCCXMi8wj1k"
reputation_chain = "9fQZEEszAi9mixRX3NrCMVY6kdC6hkfNnijfMyhUXbFo"
task_escrow = "8Exvze4gwdR1iLG8Azf7UH4g6YmB35krmf1rw9aDjaQQ"

[programs.localnet]
agent_grid = "D6QtepyhbxccbbHiLspEPYs5se7bPwznikDNDQdRNti"
reputation_chain = "GasC46imEJKa8nm9FKYvQx8i35GYSsMdF2Ag1kqKeRsi"
task_escrow = "58vuS5cVcddiYcvaANU6cu4UswpDATvKT3srkHADZKtq"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy"
test = "anchor test"

[hooks]
